# Movie DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: postgres
        image: {{ .Values.movieDb.image }}
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: configmapmovie
              key: username

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pwdmovie
              key: password
        - name: POSTGRES_DB
          value: {{ .Values.movieDb.dbName }}
        volumeMounts:
        - name: movie-db-data
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: movie-db-data
        persistentVolumeClaim:
          claimName: {{ .Values.movieDb.pvc }}

---

# Cast DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
      - name: postgres
        image: {{ .Values.castDb.image }}
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pwdcast
              key: password

        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: configmapcast
              key: username
        - name: POSTGRES_DB
          value: {{ .Values.castDb.dbName }}
        volumeMounts:
        - name: cast-db-data
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: cast-db-data
        persistentVolumeClaim:
          claimName: {{ .Values.castDb.pvc }}

---

# Movie Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: {{ .Values.movieService.image }}
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--loop", "asyncio"]
        env:
        - name: DATABASE_URI
          value: {{ .Values.movieService.dbUri }}
        ports:
        - containerPort: {{ .Values.movieService.port }}

---

# Cast Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: {{ .Values.castService.image }}
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--loop", "asyncio"]
        env:
        - name: DATABASE_URI
          value: {{ .Values.castService.dbUri }}
        ports:
        - containerPort: {{ .Values.castService.port }}

---

# NGINX
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nginx.image }}
        ports:
        - containerPort: {{ .Values.nginx.port }}
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: config
        configMap:
          name: {{ .Values.nginx.configMap }}
