apiVersion: v1
kind: Secret
metadata:
  name: pwd-movie
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.movieDb.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pwd-cast
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.castDb.password }}