apiVersion: v1
kind: Secret
metadata:
  name: pwd-movie
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.auth.movie.pass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pwd-cast
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  password: {{ .Values.auth.cast.pass }}