{{- /* Services pour les Bases de Donn√©es */ -}}
{{- range $db := list "movie-db" "cast-db" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $db }}
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ $db }}
  ports:
    - protocol: TCP
      port: {{ $.Values.service.dbPort }}
      targetPort: {{ $.Values.service.dbPort }}
---
{{- end }}

{{- /* Services pour les API (Apps) */ -}}
{{- range $app := list "movie-service" "cast-service" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app }}
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: {{ $app }}
  ports:
    - protocol: TCP
      port: {{ $.Values.service.appPort }}
      targetPort: {{ $.Values.service.appPort }}
---
{{- end }}

{{- /* Service pour Nginx (Exposition) */ -}}
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
      {{- if .Values.nginx.nodePort }}
      nodePort: {{ .Values.nginx.nodePort }}
      {{- end }}