apiVersion: v2
name: movie-cast-application
description: Helm chart pour l'examen DevOps - Services Movie et Cast avec PostgreSQL et Nginx
type: application

# Version du Chart Helm (à incrémenter à chaque modification du package)
version: 1.0.0

# Version de l'application elle-même (votre code Python/Docker)
appVersion: "1.2.0"
