auth:
  movie:
    user: "movie_db_username"
    pass: "movie_db_password"
    dbName: "movie_db_dev"
  cast:
    user: "cast_db_username"
    pass: "cast_db_password"
    dbName: "cast_db_dev"

images:
  movie: lisandru1208/movie-service:latest
  cast: lisandru1208/cast-service:latest
  postgres: postgres:12.1-alpine
  nginx: nginx:latest

nginx:
  port: 8080
  nodePort: 5432

service:
  dbPort: 5432
  appPort: 8000
  nginxPort: 8081

storage:
  size: 1Gi
  class: standard